language: objective-c

install:
    - ./scripts/install_swiftlint.sh
script:
  - swiftlint
  - xctool build test -project TravisCITest.xcodeproj -scheme TravisCITest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
